# Exceptions, catch, and throw

> 现实中错误是会发生的. 好的程序员会预料到错误并且很优雅的处理好. 但是这并不简单. 代码经常会出现无法预知的错误. 比如打开一个不存在的文件就是个致命的错误.

> 传统的办法是使用返回值. open 方法返回一些指定的值来告知失败了. 这个值通过逐层传送给负责处理的人. 这种办法要是处理所有的错误就会很痛苦. 如果一个方法调用open 然后read最后close如果这些 方法每一个都返回错误提示, 那么方法该如何在返回值中区分这么多的错误代码如何返回给调用者呢?

> 很大程度上, 异常解决了这个问题. 异常可以让你将错误信息打包到一个对象里面. 异常对象被自动传送给调用 stack, 直到运行时系统找到处理代码.
